# Generated by Django 5.0 on 2025-10-08 07:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Area Name')),
                ('total_capacity', models.IntegerField(default=0)),
                ('area_type', models.CharField(choices=[('street', 'Street'), ('garage', 'Garage'), ('lot', 'Lot')], max_length=50)),
                ('boundary', models.JSONField(blank=True, help_text='List of coordinates defining area boundary', null=True)),
            ],
            options={
                'verbose_name': 'Parking Area',
                'verbose_name_plural': 'Parking Areas',
            },
        ),
        migrations.CreateModel(
            name='RoadNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('path', models.JSONField(blank=True, help_text='List of coordinates defining the road segment', null=True)),
                ('travel_weight', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'Road Network Segment',
                'verbose_name_plural': 'Road Network Segments',
            },
        ),
        migrations.CreateModel(
            name='GarageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50)),
                ('level_capacity', models.IntegerField(default=0)),
                ('boundary', models.JSONField(blank=True, help_text='List of coordinates defining level boundary', null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='parking.parkingarea')),
            ],
            options={
                'verbose_name': 'Garage Level',
                'verbose_name_plural': 'Garage Levels',
                'unique_together': {('area', 'level_name')},
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.CharField(max_length=20, verbose_name='Slot ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_handicapped', models.BooleanField(default=False)),
                ('reserved_for', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.parkingarea')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.garagelevel')),
            ],
            options={
                'verbose_name': 'Parking Slot',
                'verbose_name_plural': 'Parking Slots',
                'unique_together': {('slot_id', 'area')},
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='parking.parkingslot')),
            ],
        ),
        migrations.CreateModel(
            name='SlotStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statuses', to='parking.sensor')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='parking.parkingslot')),
            ],
            options={
                'verbose_name': 'Slot Status',
                'verbose_name_plural': 'Slot Statuses',
                'ordering': ['-timestamp'],
            },
        ),
    ]
