# Generated by Django 5.0 on 2025-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingarea',
            name='occupied_count',
            field=models.IntegerField(default=0),
        ),
    ]
