# Generated by Django 5.0 on 2025-10-15 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parkingarea_occupied_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parking.parkingslot')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
