# Generated by Django 5.0 on 2025-10-15 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingsession',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='parking.userprofile'),
            preserve_default=False,
        ),
    ]
